### ISSUE TITLE
"Infinite Recursion Occurred" when using which-key/nix-colors

### ISSUE THREAD

**Issue by jhilker98** [dwarfmaster/home-nix#1]
Hey there, 

I was attempting to use your which-key plugin and your nix-colors plugin that you have configured for [nixvim](https://github.com/pta2002/nixvim), but I found that I got an infinite recursion error whenever I tried to use them:

```
error: infinite recursion encountered

       at /nix/store/if56vv9237zafkzgzcdkqxf2lmp86myq-source/lib/modules.nix:719:9:

          718|     in warnDeprecation opt //
          719|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          720|         inherit (res.defsFinal') highestPrio;
(use '--show-trace' to show detailed location information)
```

I've included my sample config [here](https://gist.github.com/jhilker1/ed545e0393a21aed183128517c068a6b), and for those plugins, I had just copied and pasted what you had in your files for both of those. What do I need to do in order to fix this?

**Comment by dwarfmaster** [comment]
That's strange... How do you build it ?

**Comment by jhilker1** [comment]
I just copy and pasted your exact code for the which-key plugin, and then I imported that into the neovim config

**Comment by dwarfmaster** [comment]
I don't have that problem :thinking: How do you build the resulting configuration ? With `home-manager build` ?

**Comment by dwarfmaster** [comment]
Maybe your version of nixpkgs is newer than mine. I will try updating mine to see if it causes a problem.

**Comment by jhilker1** [comment]
Alright - [here](https://gist.github.com/jhilker1/ed545e0393a21aed183128517c068a6b) is my sample config I had tried it with.

**Comment by dwarfmaster** [comment]
Turns out after updating nixpkgs I also have an infinite recursion on my config, so I can reproduce the bug.

**Comment by jhilker1** [comment]
Oh alright

**Comment by dwarfmaster** [comment]
I believe something has changed with nixvim which causes the recursion, since it looks like setting anything is causing the infinite recursion. This means it may take a bit of time to fix.

**Comment by jhilker1** [comment]
No worries! It might be related to home-manager switching to lua for its config for neovim?

**Comment by dwarfmaster** [comment]
No I think its due to the last commit on nixvim, that refactors many things to allow configurations independently of home-manager. If you pin nixvim to the previous commit it should work for the time being.

**Comment by jhilker1** [comment]
Alright, I'll try that, thanks

**Comment by jhilker1** [comment]
Thanks, that fixed it

**Comment by dwarfmaster** [comment]
You can now use the last version of nixvim, I updated my modules definitions. Feel free to reopen the issue if something's wrong with it.

**Comment by jhilker1** [comment]
Thanks for the update!
